version: '3.8'

services:

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: fraud_detection_api
    ports:
      - "8000:8000"
    networks:
      - fraud_network
    restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    container_name: fraud_detection_app
    ports:
      - "8501:8501"
    depends_on:
      - api
    environment:
      - API_URL=http://api:8000
    networks:
      - fraud_network
    restart: always

networks:
  fraud_network:
    driver: bridge